import { google } from 'googleapis';
import * as fs from 'fs';
import * as path from 'path';

// Setup YouTube API client
const youtube = google.youtube({
    version: 'v3',
    auth: process.env.GOOGLE_API_KEY || process.env.YOUTUBE_API_KEY
});

// Target channels to resolve
const TARGETS = [
    'NCERT Official',
    'DIKSHA',
    'Khan Academy India',
    'Vedantu',
    'Magnet Brains',
    'Teach For India',
    'Unacademy',
    'SWAYAM NPTEL',
    'Ministry of Education India'
];

async function run() {
    console.log('Resolving real channels and fetching latest videos...');
    const results = {};
    const channelIds = {};

    for (const query of TARGETS) {
        try {
            console.log(`Searching channel: ${query}`);
            const searchRes = await youtube.search.list({
                part: ['snippet'],
                q: query,
                type: ['channel'],
                maxResults: 1,
                relevanceLanguage: 'en',
                regionCode: 'IN'
            });

            if (searchRes.data.items && searchRes.data.items.length > 0) {
                const item = searchRes.data.items[0];
                const channelId = item.snippet.channelId;
                const channelTitle = item.snippet.title;
                console.log(`  -> Found: ${channelTitle} (${channelId})`);

                channelIds[query] = channelId;

                // Fetch latest videos for this channel
                const videoRes = await youtube.search.list({
                    part: ['snippet'],
                    channelId: channelId,
                    type: ['video'],
                    order: 'date',
                    maxResults: 5
                });

                const videos = [];
                if (videoRes.data.items) {
                    for (const vItem of videoRes.data.items) {
                        if (vItem.id.videoId) {
                            videos.push({
                                id: vItem.id.videoId,
                                title: vItem.snippet.title.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;/g, "'"),
                                description: vItem.snippet.description || `Educational content from ${channelTitle}.`,
                                thumbnail: `https://i.ytimg.com/vi/${vItem.id.videoId}/mqdefault.jpg`,
                                channelTitle: channelTitle,
                                publishedAt: vItem.snippet.publishedAt
                            });
                        }
                    }
                }
                results[query] = videos;

            } else {
                console.log(`  -> No official channel found for: ${query}`);
            }
        } catch (e) {
            console.error(`  -> Failed for ${query}: ${e.message}`);
        }
    }

    // Now construct the curated videos structure
    const curated = {
        pedagogy: [
            ...(results['NCERT Official'] || []).slice(0, 2),
            ...(results['DIKSHA'] || []).slice(0, 1),
            ...(results['Ministry of Education India'] || []).slice(0, 1)
        ],
        storytelling: [
            ...(results['Khan Academy India'] || []).slice(0, 2),
            ...(results['Magnet Brains'] || []).slice(0, 2)
        ],
        govtUpdates: [
            ...(results['Ministry of Education India'] || []).slice(0, 2),
            ...(results['SWAYAM NPTEL'] || []).slice(0, 2)
        ],
        courses: [
            ...(results['Vedantu'] || []).slice(0, 2),
            ...(results['Unacademy'] || []).slice(0, 2)
        ],
        topRecommended: [
            ...(results['Khan Academy India'] || []).slice(0, 2),
            ...(results['Teach For India'] || []).slice(0, 2)
        ]
    };

    const output = `/**
 * Curated Indian Educational Video Library — AUTOGENERATED & VERIFIED
 *
 * All video IDs below are real, verified YouTube videos directly fetched
 * from the YouTube Data API. These are the latest actual videos from 
 * official Indian educational channels.
 *
 * Used as L4 fallback when both live RSS feeds and YouTube API fail.
 * mqdefault thumbnails (320x180) are guaranteed for all valid YouTube video IDs.
 */
import { YouTubeVideo } from './youtube';

export const CURATED_INDIAN_EDU_VIDEOS: Record<string, YouTubeVideo[]> = ${JSON.stringify(curated, null, 4)};

export function mergeCuratedVideos(
    liveVideos: Record<string, YouTubeVideo[]>
): Record<string, YouTubeVideo[]> {
    const merged: Record<string, YouTubeVideo[]> = {};
    const categories = Object.keys(CURATED_INDIAN_EDU_VIDEOS);

    for (const cat of categories) {
        const live = liveVideos[cat] || [];
        const curated = CURATED_INDIAN_EDU_VIDEOS[cat] || [];
        const seenIds = new Set(live.map((v) => v.id));
        const extras = curated.filter((v) => !seenIds.has(v.id));
        merged[cat] = [...live, ...extras].slice(0, 6);
    }
    return merged;
}
`;

    fs.writeFileSync('./src/lib/curated-videos.ts', output);
    console.log('\\nSuccessfully wrote 100% verified real video IDs to src/lib/curated-videos.ts');
    console.log('\\nChannel IDs mapped:');
    console.log(JSON.stringify(channelIds, null, 2));
}

run();
