"""Class gate: every repo path referenced by the shadow-ramp preflight script exists.

Bug class: a preflight gate that greps / reads a file which does not exist
(or lives at a different path than the script believes) can NEVER pass, so
the shadow ramp is silently blocked (e.g. gate 1 pointed at
``sahayakai-main/.github/workflows/cloud-run.yml``; workflows live at the
repo-root ``.github/workflows/``). This test parses the script, extracts
every repo path it mentions (code, comments and remedy hints) and asserts
each exists. Files that are legitimately GENERATED, not committed, must be
listed in ``GENERATED_ALLOWLIST`` with a reason.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

AGENTS_DIR = Path(__file__).resolve().parents[2]
REPO_ROOT = AGENTS_DIR.parent
SCRIPT = AGENTS_DIR / "scripts" / "preflight-shadow-ramp.sh"

# Paths in the script may be written relative to any of these (the remedy
# hints say `cd sahayakai-agents && ...` / `cd sahayakai-main && ...`).
BASES = (REPO_ROOT, AGENTS_DIR, REPO_ROOT / "sahayakai-main")

# Path -> reason it is allowed to be absent from the committed tree.
GENERATED_ALLOWLIST: dict[str, str] = {
    "sahayakai-agents/tests/fixtures/parent_call_turns.json": (
        "Generated by `npm run record:parent-call-fixtures` in sahayakai-main; "
        "needs live Gemini access (GOOGLE_GENAI_API_KEY). Preflight gate 15 "
        "exists precisely to check that it has been recorded and committed."
    ),
}

_KNOWN_ROOTS = {
    "sahayakai-main",
    "sahayakai-agents",
    "scripts",
    "cloud_functions",
    "tests",
    "auto_abort",
    "shadow_diff_aggregator",
    ".github",
    "src",
    "docs",
    "prompts",
    "deploy",
}
_FILE_EXTS = (".sh", ".py", ".yaml", ".yml", ".json", ".md", ".ts", ".txt")
_TOKEN = re.compile(r"(?:\$\{ROOT\}/)?[A-Za-z0-9_.\-]+(?:/[A-Za-z0-9_.\-]+)*/?")
_URL = re.compile(r"https?://\S+")


def _tracked_basenames() -> set[str]:
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "ls-files"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.splitlines()
    except Exception:  # pragma: no cover - git unavailable
        return set()
    return {Path(p).name for p in out}


def referenced_paths(text: str) -> set[str]:
    """Extract repo-path-looking tokens (after dropping URLs)."""
    text = _URL.sub(" ", text)
    found: set[str] = set()
    for m in _TOKEN.finditer(text):
        tok = m.group(0)
        start = m.start()
        # Skip the tail of absolute paths such as /tmp/preflight.url.
        if start > 0 and text[start - 1] == "/":
            continue
        has_root_var = tok.startswith("${ROOT}/")
        tok = tok.removeprefix("${ROOT}/").rstrip(".")
        if "/" in tok:
            first = tok.split("/", 1)[0]
            if has_root_var or first in _KNOWN_ROOTS:
                found.add(tok.rstrip("/"))
        elif tok.endswith(_FILE_EXTS) and not tok.startswith("."):
            found.add(tok)
    return found


def _allowlisted(p: str) -> bool:
    """True if p is an allowlisted path or a shorter relative spelling of one."""
    return any(k == p or k.endswith("/" + p) for k in GENERATED_ALLOWLIST)


def _exists(p: str, basenames: set[str]) -> bool:
    if "/" not in p:
        return p in basenames or any((b / p).exists() for b in BASES)
    return any((b / p).exists() for b in BASES)


def test_script_exists() -> None:
    assert SCRIPT.is_file()


def test_extractor_catches_the_original_bug() -> None:
    sample = 'grep -q x "${ROOT}/sahayakai-main/.github/workflows/cloud-run.yml"'
    paths = referenced_paths(sample)
    assert "sahayakai-main/.github/workflows/cloud-run.yml" in paths
    assert not _exists(next(iter(paths)), set())


def test_extractor_ignores_urls_absolute_and_firestore_paths() -> None:
    sample = (
        "curl https://firestore.googleapis.com/v1/projects/x/documents/"
        "system_config/feature_flags /tmp/preflight.url application/json "
        "/healthz roles/run.invoker"
    )
    assert referenced_paths(sample) == set()


def test_every_referenced_path_exists_or_is_allowlisted() -> None:
    paths = referenced_paths(SCRIPT.read_text())
    assert paths, "extractor found no paths - parser is broken"
    basenames = _tracked_basenames()
    missing = sorted(p for p in paths if not _exists(p, basenames) and not _allowlisted(p))
    assert not missing, (
        "preflight-shadow-ramp.sh references paths that do not exist "
        f"(a gate on them can never pass): {missing}. Fix the path, or if the "
        "file is generated add it to GENERATED_ALLOWLIST with a reason."
    )


def test_allowlist_entries_are_referenced_and_justified() -> None:
    paths = referenced_paths(SCRIPT.read_text())
    for p, reason in GENERATED_ALLOWLIST.items():
        assert any(_allowlisted(q) and (p == q or p.endswith("/" + q)) for q in paths), (
            f"stale allowlist entry (script no longer references it): {p}"
        )
        assert len(reason) > 20, f"allowlist entry {p} needs a real reason"
