// File generated by FlutterFire CLI.
// Run `flutterfire configure --project=sahayakai-b4248` after
// `firebase login` to regenerate with proper Android/iOS app IDs.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgCKW4e6YpM4HHIgAhwhJwmyQ0wRGCtw',
    appId: '1:640589855975:web:624436f873a78069aa3642',
    messagingSenderId: '640589855975',
    projectId: 'sahayakai-b4248',
    storageBucket: 'sahayakai-b4248.firebasestorage.app',
  );

  // TODO: Run `flutterfire configure --project=sahayakai-b4248
  //       --platforms=android --android-package-name=app.sahayakai.mobile`
  //       after `firebase login` to populate the correct Android appId
  //       and download google-services.json to android/app/.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKgCKW4e6YpM4HHIgAhwhJwmyQ0wRGCtw',
    appId: '1:640589855975:android:REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: '640589855975',
    projectId: 'sahayakai-b4248',
    storageBucket: 'sahayakai-b4248.firebasestorage.app',
  );

  // TODO: Run `flutterfire configure --project=sahayakai-b4248
  //       --platforms=ios --ios-bundle-id=app.sahayakai.mobile`
  //       after `firebase login` to populate the correct iOS appId
  //       and download GoogleService-Info.plist to ios/Runner/.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKgCKW4e6YpM4HHIgAhwhJwmyQ0wRGCtw',
    appId: '1:640589855975:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '640589855975',
    projectId: 'sahayakai-b4248',
    storageBucket: 'sahayakai-b4248.firebasestorage.app',
    iosBundleId: 'app.sahayakai.mobile',
  );
}
