import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../../core/theme/glassmorphic/glass_components.dart';
import 'submit_content_screen.dart';

// ─────────────────── Data models ───────────────────

class _Post {
  final String author;
  final String role;
  final String location;
  final String timeAgo;
  final String title;
  final String content;
  final int likes;
  final int comments;
  final List<String> tags;
  final Color avatarColor;
  bool isLiked;

  _Post({
    required this.author,
    required this.role,
    required this.location,
    required this.timeAgo,
    required this.title,
    required this.content,
    required this.likes,
    required this.comments,
    required this.tags,
    required this.avatarColor,
    this.isLiked = false,
  });
}

final _feedPosts = [
  _Post(
    author: 'Priya Sharma',
    role: 'Science Teacher',
    location: 'Mumbai, MH',
    timeAgo: '2h ago',
    title: 'Interactive Solar System Lesson',
    content: 'Just created a VR-based lesson plan for the solar system using SahayakAI. Students were completely engaged — even the ones who usually struggle! Sharing the resource below.',
    likes: 42,
    comments: 8,
    tags: ['Science', 'VR', 'Class 6'],
    avatarColor: Color(0xFF7C3AED),
  ),
  _Post(
    author: 'Ramesh Gupta',
    role: 'Math Department Head',
    location: 'Delhi',
    timeAgo: '5h ago',
    title: 'Vedic Math Tricks for Division',
    content: 'Vedic Math trick for long division — calculation speed improved 50% in my Class 8. Worksheet attached with 3 difficulty levels generated by SahayakAI.',
    likes: 87,
    comments: 19,
    tags: ['Math', 'Vedic', 'Tips'],
    avatarColor: Color(0xFF0891B2),
    isLiked: true,
  ),
  _Post(
    author: 'Anjali Desai',
    role: 'History Teacher',
    location: 'Pune, MH',
    timeAgo: '1d ago',
    title: 'Mughal Empire Visual Timeline',
    content: 'Created a visual timeline for the Mughal Empire using the Visual Aid tool. My students now remember historical dates much better!',
    likes: 31,
    comments: 4,
    tags: ['History', 'Class 7', 'Visuals'],
    avatarColor: Color(0xFFD97706),
  ),
  _Post(
    author: 'Kavya Nair',
    role: 'English Teacher',
    location: 'Kochi, KL',
    timeAgo: '2d ago',
    title: 'Story Writing with AI in Malayalam',
    content: 'Used SahayakAI to generate story prompts for Class 4 students in Malayalam. The AI understood cultural context — it mentioned Onam and Kerala landscapes!',
    likes: 56,
    comments: 14,
    tags: ['Malayalam', 'English', 'Class 4'],
    avatarColor: Color(0xFF059669),
  ),
];

final _teachers = [
  {'name': 'Dr. Meera Pillai', 'subject': 'Physics · Class 11-12', 'school': 'KV Trivandrum', 'followers': 234, 'color': 0xFF7C3AED},
  {'name': 'Arjun Singh', 'subject': 'Hindi · Class 6-8', 'school': 'Govt. School, Jaipur', 'followers': 189, 'color': 0xFF0891B2},
  {'name': 'Fatima Khan', 'subject': 'Chemistry · Class 9-10', 'school': 'Hyderabad', 'followers': 312, 'color': 0xFFD97706},
  {'name': 'Suresh Babu', 'subject': 'Social Studies', 'school': 'Chennai', 'followers': 145, 'color': 0xFF059669},
];

const _filterChips = ['All', 'Science', 'Math', 'Hindi', 'English', 'History', 'Regional'];

// ─────────────────── Community Feed Screen ───────────────────

class CommunityFeedScreen extends ConsumerStatefulWidget {
  const CommunityFeedScreen({super.key});

  @override
  ConsumerState<CommunityFeedScreen> createState() => _CommunityFeedScreenState();
}

class _CommunityFeedScreenState extends ConsumerState<CommunityFeedScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  String _selectedFilter = 'All';
  final List<_Post> _posts = List.from(_feedPosts);

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(gradient: GlassColors.warmBackgroundGradient),
      child: Column(
        children: [
          _buildHeader(),
          _buildTabBar(),
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: [
                _buildFeedTab(),
                _buildDiscoverTab(),
                _buildChatComingSoon(),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return Padding(
      padding: const EdgeInsets.fromLTRB(20, 16, 20, 0),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Teacher Hub',
                  style: GoogleFonts.outfit(
                    fontSize: 26,
                    fontWeight: FontWeight.w800,
                    color: GlassColors.textPrimary,
                  ),
                ),
                Text(
                  'Connect · Share · Grow',
                  style: GlassTypography.bodySmall(color: GlassColors.textSecondary),
                ),
              ],
            ),
          ),
          GestureDetector(
            onTap: () => Navigator.push(
              context,
              MaterialPageRoute(builder: (_) => const SubmitContentScreen()),
            ),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [Color(0xFFFF9933), Color(0xFFE68A00)],
                ),
                borderRadius: BorderRadius.circular(20),
                boxShadow: [
                  BoxShadow(
                    color: const Color(0xFFFF9933).withValues(alpha: 0.3),
                    blurRadius: 10,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Icon(Icons.add_rounded, color: Colors.white, size: 16),
                  const SizedBox(width: 4),
                  Text(
                    'Post',
                    style: GoogleFonts.outfit(
                      fontSize: 13,
                      fontWeight: FontWeight.w700,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTabBar() {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.6),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFE8E8E8)),
      ),
      child: TabBar(
        controller: _tabController,
        indicator: BoxDecoration(
          color: GlassColors.primary,
          borderRadius: BorderRadius.circular(10),
        ),
        indicatorSize: TabBarIndicatorSize.tab,
        indicatorPadding: const EdgeInsets.all(3),
        labelColor: Colors.white,
        unselectedLabelColor: GlassColors.textSecondary,
        labelStyle: GoogleFonts.outfit(fontSize: 13, fontWeight: FontWeight.w600),
        unselectedLabelStyle: GoogleFonts.outfit(fontSize: 13, fontWeight: FontWeight.w500),
        dividerColor: Colors.transparent,
        tabs: const [Tab(text: 'Feed'), Tab(text: 'Discover'), Tab(text: 'Chat')],
      ),
    );
  }

  Widget _buildFeedTab() {
    return Column(
      children: [
        SizedBox(
          height: 44,
          child: ListView.builder(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            scrollDirection: Axis.horizontal,
            physics: const BouncingScrollPhysics(),
            itemCount: _filterChips.length,
            itemBuilder: (context, i) {
              final chip = _filterChips[i];
              final selected = _selectedFilter == chip;
              return GestureDetector(
                onTap: () => setState(() => _selectedFilter = chip),
                child: Container(
                  margin: const EdgeInsets.only(right: 8),
                  padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                  decoration: BoxDecoration(
                    color: selected ? GlassColors.primary : Colors.white,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                      color: selected ? GlassColors.primary : const Color(0xFFE8E8E8),
                    ),
                    boxShadow: selected ? [
                      BoxShadow(
                        color: GlassColors.primary.withValues(alpha: 0.25),
                        blurRadius: 8,
                        offset: const Offset(0, 2),
                      ),
                    ] : [],
                  ),
                  child: Text(
                    chip,
                    style: GoogleFonts.outfit(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: selected ? Colors.white : GlassColors.textSecondary,
                    ),
                  ),
                ),
              );
            },
          ),
        ),
        const SizedBox(height: 8),
        Expanded(
          child: ListView.builder(
            padding: const EdgeInsets.fromLTRB(20, 4, 20, 20),
            physics: const BouncingScrollPhysics(),
            itemCount: _posts.length,
            itemBuilder: (context, i) => _PostCard(
              post: _posts[i],
              onLike: () => setState(() => _posts[i].isLiked = !_posts[i].isLiked),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDiscoverTab() {
    return ListView(
      padding: const EdgeInsets.fromLTRB(20, 8, 20, 80),
      physics: const BouncingScrollPhysics(),
      children: [
        Text('Teachers to Follow', style: GlassTypography.headline3()),
        const SizedBox(height: 12),
        ..._teachers.map((t) => _TeacherCard(data: t)),
        const SizedBox(height: 20),
        Text('Trending Topics', style: GlassTypography.headline3()),
        const SizedBox(height: 12),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: [
            '#NEP2020', '#BilingualTeaching', '#VedicMath',
            '#ProjectBased', '#MultigradeClass', '#DigitalLiteracy',
            '#InclusiveEd', '#STEMIndia', '#LanguageLearning',
          ].map((tag) => Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(20),
              border: Border.all(color: const Color(0xFFE8E8E8)),
            ),
            child: Text(
              tag,
              style: GoogleFonts.outfit(
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: GlassColors.textSecondary,
              ),
            ),
          )).toList(),
        ),
      ],
    );
  }

  Widget _buildChatComingSoon() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(40),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 80,
              height: 80,
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [Color(0xFFFF9933), Color(0xFFE68A00)],
                ),
                borderRadius: BorderRadius.circular(24),
              ),
              child: const Icon(Icons.chat_bubble_rounded, color: Colors.white, size: 40),
            ),
            const SizedBox(height: 20),
            Text('Staff Room Chat', style: GlassTypography.headline2()),
            const SizedBox(height: 8),
            Text(
              'Live chat with 10M+ teachers across India — coming soon',
              style: GlassTypography.bodyMedium(color: GlassColors.textSecondary),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }
}

// ─────────────────── Post Card ───────────────────

class _PostCard extends StatelessWidget {
  final _Post post;
  final VoidCallback onLike;

  const _PostCard({required this.post, required this.onLike});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: const Color(0xFFE8E8E8)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 12,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              children: [
                CircleAvatar(
                  radius: 20,
                  backgroundColor: post.avatarColor.withValues(alpha: 0.12),
                  child: Text(
                    post.author[0],
                    style: GoogleFonts.outfit(
                      fontSize: 16,
                      fontWeight: FontWeight.w700,
                      color: post.avatarColor,
                    ),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(post.author, style: GlassTypography.labelLarge()),
                      Text('${post.role} · ${post.location}', style: GlassTypography.bodySmall()),
                    ],
                  ),
                ),
                Text(post.timeAgo, style: GlassTypography.bodySmall()),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(post.title, style: GlassTypography.headline3()),
                const SizedBox(height: 6),
                Text(
                  post.content,
                  style: GlassTypography.bodyMedium(color: GlassColors.textSecondary),
                  maxLines: 3,
                  overflow: TextOverflow.ellipsis,
                ),
                const SizedBox(height: 10),
                Wrap(
                  spacing: 6,
                  runSpacing: 6,
                  children: post.tags.map((tag) => Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                    decoration: BoxDecoration(
                      color: const Color(0xFFF3F4F6),
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: Text(
                      '#$tag',
                      style: GoogleFonts.outfit(
                        fontSize: 11,
                        fontWeight: FontWeight.w500,
                        color: GlassColors.textSecondary,
                      ),
                    ),
                  )).toList(),
                ),
              ],
            ),
          ),
          const Divider(height: 1, color: Color(0xFFF3F4F6)),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
            child: Row(
              children: [
                _ActionBtn(
                  icon: post.isLiked ? Icons.favorite_rounded : Icons.favorite_border_rounded,
                  label: '${post.likes + (post.isLiked ? 1 : 0)}',
                  color: post.isLiked ? const Color(0xFFEC4899) : GlassColors.textSecondary,
                  onTap: onLike,
                ),
                _ActionBtn(
                  icon: Icons.chat_bubble_outline_rounded,
                  label: '${post.comments}',
                  color: const Color(0xFF3B82F6),
                  onTap: () {},
                ),
                _ActionBtn(
                  icon: Icons.bookmark_border_rounded,
                  label: 'Save',
                  color: GlassColors.textSecondary,
                  onTap: () {},
                ),
                _ActionBtn(
                  icon: Icons.share_rounded,
                  label: 'Share',
                  color: GlassColors.textSecondary,
                  onTap: () {},
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _ActionBtn extends StatelessWidget {
  final IconData icon;
  final String label;
  final Color color;
  final VoidCallback onTap;

  const _ActionBtn({required this.icon, required this.label, required this.color, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: GestureDetector(
        onTap: onTap,
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 8),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(icon, size: 18, color: color),
              const SizedBox(width: 4),
              Text(label, style: GoogleFonts.outfit(fontSize: 12, fontWeight: FontWeight.w600, color: color)),
            ],
          ),
        ),
      ),
    );
  }
}

// ─────────────────── Teacher Card ───────────────────

class _TeacherCard extends StatefulWidget {
  final Map<String, dynamic> data;
  const _TeacherCard({required this.data});

  @override
  State<_TeacherCard> createState() => _TeacherCardState();
}

class _TeacherCardState extends State<_TeacherCard> {
  bool _following = false;

  @override
  Widget build(BuildContext context) {
    final color = Color(widget.data['color'] as int);
    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE8E8E8)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.03),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Row(
        children: [
          CircleAvatar(
            radius: 22,
            backgroundColor: color.withValues(alpha: 0.12),
            child: Text(
              (widget.data['name'] as String)[0],
              style: GoogleFonts.outfit(fontSize: 16, fontWeight: FontWeight.w700, color: color),
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(widget.data['name'] as String, style: GlassTypography.labelLarge()),
                Text(widget.data['subject'] as String, style: GlassTypography.bodySmall()),
                Text(
                  '${widget.data['followers']} followers',
                  style: GlassTypography.bodySmall(color: GlassColors.textTertiary),
                ),
              ],
            ),
          ),
          GestureDetector(
            onTap: () => setState(() => _following = !_following),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 7),
              decoration: BoxDecoration(
                color: _following ? const Color(0xFFF3F4F6) : GlassColors.primary,
                borderRadius: BorderRadius.circular(20),
                border: _following ? Border.all(color: const Color(0xFFE8E8E8)) : null,
              ),
              child: Text(
                _following ? 'Following' : 'Follow',
                style: GoogleFonts.outfit(
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  color: _following ? GlassColors.textSecondary : Colors.white,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
