'use server';

import { z } from 'zod';
import { ai } from '@/ai/genkit';
import { validateMicroLessonPayload } from '@/tools/validate_micro_lesson';
import { getIndianContextPrompt } from '@/lib/indian-context';
import {
    saveContent,
    generateCacheKey,
    getCachedContent,
    saveToCache
} from '@/lib/content-persistence';
import { logger, logError } from '@/lib/cloud-logging';

// 1. Define Input Schema (State Management)
const MicroLessonInputSchema = z.object({
    topic: z.string().describe("The main chapter or topic e.g., 'Chapter 2: Nutrition in Animals'"),
    subject: z.string().optional().describe("Subject e.g., 'Science'"),
    gradeLevel: z.string().describe("Target grade level e.g., '7th Grade'"),
    sequenceNumber: z.number().default(1).describe("1 for first part..."),
    previousLessonContext: z.string().optional().describe("Context for continuity"),
    language: z.string().default('English').describe("Language of instruction (e.g. Hindi, Tamil)"),
    userId: z.string().optional().describe("User ID for persisting generated content"),
});

// 2. Define Output Schema
const SlideContentSchema = z.object({
    title: z.string(),
    bulletPoints: z.array(z.string()),
    visualPrompt: z.string().optional().describe("Detailed image generation prompt. MANDATORY for Concept/Example slides."),
    teacherNotes: z.string(),
    imageUrl: z.string().optional().describe("Generated image URL"),
});

const SlideSchema = z.object({
    slideNumber: z.number(),
    type: z.enum(['Title', 'introduction', 'Concept', 'Content', 'Explanation', 'Example', 'Activity', 'Summary']),
    content: SlideContentSchema,
});

const MicroLessonOutputSchema = z.object({
    topic: z.string(),
    subject: z.string().optional(),
    gradeLevel: z.string(),
    language: z.string().optional(),
    sequenceNumber: z.number(),
    slides: z.array(SlideSchema),
});

export type MicroLessonInput = z.infer<typeof MicroLessonInputSchema>;
export type MicroLessonOutput = z.infer<typeof MicroLessonOutputSchema>;

// 3. Define the Prompt (Refined for Academic Quality)
const microLessonPrompt = ai.definePrompt(
    {
        name: 'microLessonPrompt',
        model: 'googleai/gemini-2.0-flash',
        input: { schema: MicroLessonInputSchema },
        output: { schema: MicroLessonOutputSchema },
    },
    `
  You are an expert Professor of {{subject}}. Create a high-quality **Lecture Slide Deck** (7-10 slides) for {{gradeLevel}} students on "{{topic}}".
  
  **Language Instruction:** The content must be in **{{language}}**.

  **Pedagogical Strategy:**
  - **Academic Rigor:** Start with precise definitions. Then explain mechanisms.
  - **Directness:** Avoid fluff like "Imagine..." or "Let's think about...". Use direct statements: "Mass is..."
  - **Deep Dive:** Don't just list facts. Explain *why* things happen.
  - **Key Terms:** Use **bold** syntax for key terms (e.g., "**Photosynthesis** is the process...").

  **Structure:**
  1. **Title Slide:** Huge Title, Subtitle (Subject).
  2. **The "Big Question" (Intro):** Start with a provocative question/hook about the utility of the topic.
  3. **Concept Breakdown (3-4 Slides):**
     - Each slide focuses on ONE key idea.
     - **MANDATORY:** Provide a 'visualPrompt' for EVERY Concept slide describing a diagram/illustration.
     - Example visualPrompt: "A cross-section of a plant cell clearly showing the cell wall and nucleus, textbook style."
  4. **The "Bharat" Analogy:** A dedicated slide explaining the concept using a specific Indian context.
  5. **Summary & Homework:** Recap + 1 easy activity.

  **Requirements:**
  - **visualPrompt**: Must be detailed and provided for **at least 4 slides**. DO NOT LEAVE EMPTY.
  - **Tone**: Engaging, storytelling, authoritative.
  
  ${getIndianContextPrompt()}
  `
);

// 4. Define the Flow
export const microLessonFlow = ai.defineFlow(
    {
        name: 'microLessonFlow',
        inputSchema: MicroLessonInputSchema,
        outputSchema: MicroLessonOutputSchema,
    },
    async (input) => {
        // Generate content
        const { output } = await microLessonPrompt(input);

        if (!output) {
            throw new Error("AI failed to generate lesson content.");
        }

        // Image Generation
        // We filter slides with active visual prompts.
        const slidesToIllustrate = output.slides
            .filter(s => s.content.visualPrompt && s.content.visualPrompt.length > 5);
        // Removed .slice(0, 4) limit to generate images for ALL slides with prompts

        if (slidesToIllustrate.length === 0) {
            console.warn("WARN: No visual prompts generated by the text model.");
        }

        // Parallel Image Generation
        await Promise.all(slidesToIllustrate.map(async (slide) => {
            try {
                const imageRes = await ai.generate({
                    model: 'googleai/gemini-2.0-flash', // Standardizing on the faster model for slide visuals
                    prompt: `Create a high-quality educational illustration for a textbook. Subject: ${slide.content.visualPrompt}. Style: Clear, detailed, colorful, suitable for a white background. No text labels. ${getIndianContextPrompt(true)}`,
                    config: {
                        responseModalities: ['IMAGE'],
                        temperature: 0.4
                    }
                });

                if (imageRes.media) {
                    slide.content.imageUrl = imageRes.media.url;
                }
            } catch (e: any) {
                console.warn(`Failed image generation for slide ${slide.slideNumber}: ${e.message}`);
            }
        }));

        // Validation
        const validation = validateMicroLessonPayload(output);
        if (!validation.valid) {
            console.warn(`Lecture Slides Validation Warning:`, validation.errors);
        }

        return output;
    }
);

// Export async wrapper function for server actions
export async function generateMicroLesson(input: MicroLessonInput): Promise<MicroLessonOutput> {
    const { userId, topic, subject, gradeLevel, language } = input;
    const startTime = Date.now();

    // Step 1: Check cache
    const cacheKey = await generateCacheKey({
        topic,
        subject: subject || 'General',
        gradeLevel,
        language,
        contentType: 'micro-lesson',
    });

    const cachedOutput = await getCachedContent(cacheKey);
    if (cachedOutput) {
        await logger.info({
            event: 'cache_hit',
            userId,
            latencyMs: Date.now() - startTime,
            metadata: { cacheKey, contentType: 'micro-lesson' }
        });
        return cachedOutput;
    }

    await logger.info({
        event: 'cache_miss',
        userId,
        metadata: { cacheKey, contentType: 'micro-lesson' }
    });

    try {
        await logger.info({
            event: 'micro_lesson_generation_started',
            userId,
            metadata: { topic, gradeLevel, subject }
        });

        // Step 2: Generate new content
        const output = await microLessonFlow(input);

        const latencyMs = Date.now() - startTime;
        await logger.info({
            event: 'micro_lesson_generation_completed',
            userId,
            latencyMs,
            metadata: { topic, gradeLevel }
        });

        // Step 3: Persist to database (if userId provided)
        if (userId) {
            // Prepare images for unified persistence
            const imagesToSave = output.slides
                .filter(s => s.content.imageUrl && s.content.imageUrl.startsWith('data:'))
                .map(s => ({
                    buffer: Buffer.from(s.content.imageUrl!.split(',')[1], 'base64'),
                    filename: `slide_${s.slideNumber}_${Date.now()}.png`,
                    contentType: 'image/png'
                }));

            await saveContent({
                userId,
                contentType: 'micro-lesson',
                title: topic,
                content: output,
                metadata: {
                    subject,
                    gradeLevel,
                    language,
                    description: `Micro-lesson index ${input.sequenceNumber}: ${topic}`,
                },
                images: imagesToSave
            });
        }

        // Step 4: Save to cache
        await saveToCache(
            cacheKey,
            'micro-lesson',
            { topic, subject, gradeLevel, language },
            output,
            0.24
        );

        return output;
    } catch (error: any) {
        await logError({
            event: 'micro_lesson_generation_failed',
            error,
            userId,
            metadata: { topic }
        });
        throw error;
    }
}
