/// # Firebase seam (U-SI0) — documented, NOT imported
///
/// This is a **no-op stub**. The current app has **zero Firebase packages** in
/// `pubspec.yaml` (`firebase_core`, `cloud_firestore`, `firebase_database`,
/// `firebase_messaging`, `firebase_auth` are all absent) because adding any of
/// them breaks `flutter build apk` without an `android/app/google-services.json`
/// — and that file is a founder handoff wall (it carries the real project
/// config). Keeping the APK green is the whole point of the U-SI0 spike.
///
/// So this file imports **no** Firebase package. It exposes the single seam the
/// Block-C transport providers read to decide "deferred vs. live"
/// ([FirebaseInit.isConfigured], currently `false`), and documents — in the TODO
/// block below — exactly what the real wiring will be once the handoff happens.
///
/// ## The handoff (what makes Block C live)
///
/// 1. **Add the deps** to `pubspec.yaml` (pin them; do NOT float):
///    ```yaml
///    firebase_core: ^3.x        # Firebase.initializeApp
///    cloud_firestore: ^5.x      # onSnapshot reads: inbox, thread, chat, badges
///    firebase_database: ^11.x   # RTDB onValue: presence dot only (U-SI6)
///    firebase_messaging: ^15.x  # FCM push parity (U-SI6, handoff-walled)
///    ```
///    Then run `scripts/verify_build.sh` — `flutter analyze` + `flutter test`
///    NEVER compile the release kernel snapshot or invoke Gradle, so only the
///    APK build proves the native side survived (this is exactly how a stale
///    federated plugin sibling has broken the build here before while
///    analyze+test stayed green).
///
/// 2. **Drop in `google-services.json`** at `android/app/` (from the Firebase
///    console for the SahayakAI project) and apply the Google-services Gradle
///    plugin. Without it, `Firebase.initializeApp()` throws at launch.
///
/// 3. **Replace this stub's body** with the real init and flip
///    [isConfigured] to reflect it. The real implementation looks like:
///    ```dart
///    import 'package:firebase_core/firebase_core.dart';
///    import 'firebase_options.dart'; // generated by `flutterfire configure`
///
///    static bool _ready = false;
///    static Future<void> ensureInitialized() async {
///      if (_ready) return;
///      await Firebase.initializeApp(
///        options: DefaultFirebaseOptions.currentPlatform,
///      );
///      _ready = true;
///    }
///    static bool get isConfigured => _ready;
///    ```
///    Call `await FirebaseInit.ensureInitialized()` in `main()` **before**
///    `runApp`, gated so a build without the config still boots (the non-Block-C
///    app must keep working without Firebase).
///
/// 4. **Bind the real transports** to the providers. Today
///    `inboxTransportProvider` / `staffroomTransportProvider` /
///    `notificationsTransportProvider` / `presenceTransportProvider` return the
///    `Deferred*Transport`. Once [isConfigured] is `true`, return the
///    `Firestore*Transport` (reads via `cloud_firestore` `onSnapshot`, writes via
///    the Dio `ApiClient` REST wrappers). The interface — and therefore every
///    U-SI1..U-SI6 screen — does not change.
///
/// 5. **Auth token bridge.** The transports' REST writes reuse the existing
///    `ApiClient` (`Authorization: Bearer <Firebase ID token>` → server
///    `x-user-id`). `lib/core/network/api_providers.dart::tokenProvider` is still
///    the signed-out stub (`() async => null`); wiring `firebase_auth` there is
///    the same handoff (return `user?.getIdToken(forceRefresh)`).
///
/// See `docs/flutter/HANDOFF.md` §"Block C — Firebase transport handoff" for the
/// full REST-wrapper + `firestore.rules` contract, and each transport interface's
/// doc comments for the exact method → Firestore-query / REST-route mapping.
class FirebaseInit {
  const FirebaseInit._();

  /// Whether Firebase has been initialized for this process.
  ///
  /// **Always `false`** in the current build — no Firebase package is wired, so
  /// there is nothing to initialize. The Block-C transport providers read this
  /// to choose the deferred implementation; when the handoff flips it `true`
  /// (see the class doc), they return the live Firestore-backed implementation
  /// instead. Kept as a plain getter (not a `const false`) so the future real
  /// wiring can back it with an instance flag without changing call sites.
  static bool get isConfigured => false;

  /// No-op until the handoff. The real body calls `Firebase.initializeApp(...)`
  /// (see the class doc). Safe to `await` in `main()` today — it does nothing.
  static Future<void> ensureInitialized() async {
    // Intentionally empty: no Firebase package is present. Do NOT add one here
    // without also landing google-services.json, or `flutter build apk` breaks.
  }
}
