/**
 * Curated Indian Educational Video Library — AUTOGENERATED & VERIFIED
 *
 * All video IDs below are real, verified YouTube videos scraped directly
 * from the public XML RSS feeds of official Indian educational channels.
 *
 * Used as L4 fallback when both live RSS feeds and YouTube API fail.
 * mqdefault thumbnails (320x180) are guaranteed for all valid YouTube video IDs.
 */
import { YouTubeVideo } from './youtube';

export const CURATED_INDIAN_EDU_VIDEOS: Record<string, YouTubeVideo[]> = {
    "pedagogy": [
        {
            "id": "OyNil0Zkgj8",
            "title": "Sahyog : Breathing and the Brain: Techniques for Calming One's Mind",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/OyNil0Zkgj8/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-04T00:03:12+00:00"
        },
        {
            "id": "GVVdRTiRv0k",
            "title": "Day 2:  Exploring Online Course Platforms & Features",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/GVVdRTiRv0k/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-03T23:38:34+00:00"
        },
        {
            "id": "3sdfPmwcG8s",
            "title": "NCERT  अध्याय 6 जयपुर से पत्र (भाग - I)   Subject: हिन्दी    Class: IV  Live",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/3sdfPmwcG8s/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-03T22:28:07+00:00"
        },
        {
            "id": "oWGIhy24Eos",
            "title": "Post Budget Webinar 2026–27 | Education, Skills & University Townships | Towards Viksit Bharat @2047",
            "description": "Educational content from Ministry of Education India.",
            "thumbnail": "https://i.ytimg.com/vi/oWGIhy24Eos/mqdefault.jpg",
            "channelTitle": "Ministry of Education India",
            "publishedAt": "2026-03-03T08:22:36+00:00"
        },
        {
            "id": "RIOK03Ta0ZA",
            "title": "LIVE | Shri Dharmendra Pradhan Addresses Study in India Edu-Diplomatic Conclave",
            "description": "Educational content from Ministry of Education India.",
            "thumbnail": "https://i.ytimg.com/vi/RIOK03Ta0ZA/mqdefault.jpg",
            "channelTitle": "Ministry of Education India",
            "publishedAt": "2026-03-02T18:28:37+00:00"
        },
        {
            "id": "_RCw3k2aAKk",
            "title": "Bodhan.ai, AI Centre of Excellence for Education at IIT Madras Established by MoE",
            "description": "Educational content from Ministry of Education India.",
            "thumbnail": "https://i.ytimg.com/vi/_RCw3k2aAKk/mqdefault.jpg",
            "channelTitle": "Ministry of Education India",
            "publishedAt": "2026-02-18T10:26:19+00:00"
        }
    ],
    "storytelling": [
        {
            "id": "Ym1WWgG3HSI",
            "title": "Brain: Parts & functions [Marathi] | Life processes in Living Organisms | Class 9 | Science | KA",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/Ym1WWgG3HSI/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T06:35:38+00:00"
        },
        {
            "id": "WbD2694U3-g",
            "title": "Nervous system (central & peripheral) [Marathi] | Life processes in Living Organisms | Class 9 | KA",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/WbD2694U3-g/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T06:20:28+00:00"
        },
        {
            "id": "wIb4fiYbIFo",
            "title": "Antibiotics [Marathi] | Useful and Harmful Microbes | Class 9 | Science | Khan Academy",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/wIb4fiYbIFo/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T04:29:12+00:00"
        },
        {
            "id": "OyNil0Zkgj8",
            "title": "Sahyog : Breathing and the Brain: Techniques for Calming One's Mind",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/OyNil0Zkgj8/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-04T00:03:12+00:00"
        },
        {
            "id": "GVVdRTiRv0k",
            "title": "Day 2:  Exploring Online Course Platforms & Features",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/GVVdRTiRv0k/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-03T23:38:34+00:00"
        },
        {
            "id": "3sdfPmwcG8s",
            "title": "NCERT  अध्याय 6 जयपुर से पत्र (भाग - I)   Subject: हिन्दी    Class: IV  Live",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/3sdfPmwcG8s/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-03T22:28:07+00:00"
        }
    ],
    "govtUpdates": [
        {
            "id": "oWGIhy24Eos",
            "title": "Post Budget Webinar 2026–27 | Education, Skills & University Townships | Towards Viksit Bharat @2047",
            "description": "Educational content from Ministry of Education India.",
            "thumbnail": "https://i.ytimg.com/vi/oWGIhy24Eos/mqdefault.jpg",
            "channelTitle": "Ministry of Education India",
            "publishedAt": "2026-03-03T08:22:36+00:00"
        },
        {
            "id": "RIOK03Ta0ZA",
            "title": "LIVE | Shri Dharmendra Pradhan Addresses Study in India Edu-Diplomatic Conclave",
            "description": "Educational content from Ministry of Education India.",
            "thumbnail": "https://i.ytimg.com/vi/RIOK03Ta0ZA/mqdefault.jpg",
            "channelTitle": "Ministry of Education India",
            "publishedAt": "2026-03-02T18:28:37+00:00"
        },
        {
            "id": "_RCw3k2aAKk",
            "title": "Bodhan.ai, AI Centre of Excellence for Education at IIT Madras Established by MoE",
            "description": "Educational content from Ministry of Education India.",
            "thumbnail": "https://i.ytimg.com/vi/_RCw3k2aAKk/mqdefault.jpg",
            "channelTitle": "Ministry of Education India",
            "publishedAt": "2026-02-18T10:26:19+00:00"
        },
        {
            "id": "OyNil0Zkgj8",
            "title": "Sahyog : Breathing and the Brain: Techniques for Calming One's Mind",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/OyNil0Zkgj8/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-04T00:03:12+00:00"
        },
        {
            "id": "GVVdRTiRv0k",
            "title": "Day 2:  Exploring Online Course Platforms & Features",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/GVVdRTiRv0k/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-03T23:38:34+00:00"
        },
        {
            "id": "3sdfPmwcG8s",
            "title": "NCERT  अध्याय 6 जयपुर से पत्र (भाग - I)   Subject: हिन्दी    Class: IV  Live",
            "description": "Educational content from NCERT Official.",
            "thumbnail": "https://i.ytimg.com/vi/3sdfPmwcG8s/mqdefault.jpg",
            "channelTitle": "NCERT Official",
            "publishedAt": "2026-03-03T22:28:07+00:00"
        }
    ],
    "courses": [
        {
            "id": "ZfhnFr-1MPo",
            "title": "Unacademy Centre - The Power Behind You",
            "description": "Educational content from Unacademy.",
            "thumbnail": "https://i.ytimg.com/vi/ZfhnFr-1MPo/mqdefault.jpg",
            "channelTitle": "Unacademy",
            "publishedAt": "2024-03-20T11:33:57+00:00"
        },
        {
            "id": "CBDM_OhgQFI",
            "title": "Aarambh - The Journey Begins | Unacademy Centre Foundation Day | June 15, 2023",
            "description": "Educational content from Unacademy.",
            "thumbnail": "https://i.ytimg.com/vi/CBDM_OhgQFI/mqdefault.jpg",
            "channelTitle": "Unacademy",
            "publishedAt": "2023-06-24T08:23:57+00:00"
        },
        {
            "id": "gFPhYguV0ZU",
            "title": "Epic Hide & Seek Ft. @ashishchanchlanivines @SamayRainaOfficial  | Official Challenge",
            "description": "Educational content from Unacademy.",
            "thumbnail": "https://i.ytimg.com/vi/gFPhYguV0ZU/mqdefault.jpg",
            "channelTitle": "Unacademy",
            "publishedAt": "2022-11-26T15:38:46+00:00"
        },
        {
            "id": "Ym1WWgG3HSI",
            "title": "Brain: Parts & functions [Marathi] | Life processes in Living Organisms | Class 9 | Science | KA",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/Ym1WWgG3HSI/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T06:35:38+00:00"
        },
        {
            "id": "WbD2694U3-g",
            "title": "Nervous system (central & peripheral) [Marathi] | Life processes in Living Organisms | Class 9 | KA",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/WbD2694U3-g/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T06:20:28+00:00"
        },
        {
            "id": "wIb4fiYbIFo",
            "title": "Antibiotics [Marathi] | Useful and Harmful Microbes | Class 9 | Science | Khan Academy",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/wIb4fiYbIFo/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T04:29:12+00:00"
        }
    ],
    "topRecommended": [
        {
            "id": "Ym1WWgG3HSI",
            "title": "Brain: Parts & functions [Marathi] | Life processes in Living Organisms | Class 9 | Science | KA",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/Ym1WWgG3HSI/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T06:35:38+00:00"
        },
        {
            "id": "WbD2694U3-g",
            "title": "Nervous system (central & peripheral) [Marathi] | Life processes in Living Organisms | Class 9 | KA",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/WbD2694U3-g/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T06:20:28+00:00"
        },
        {
            "id": "wIb4fiYbIFo",
            "title": "Antibiotics [Marathi] | Useful and Harmful Microbes | Class 9 | Science | Khan Academy",
            "description": "Educational content from Khan Academy India.",
            "thumbnail": "https://i.ytimg.com/vi/wIb4fiYbIFo/mqdefault.jpg",
            "channelTitle": "Khan Academy India",
            "publishedAt": "2026-03-01T04:29:12+00:00"
        },
        {
            "id": "ZfhnFr-1MPo",
            "title": "Unacademy Centre - The Power Behind You",
            "description": "Educational content from Unacademy.",
            "thumbnail": "https://i.ytimg.com/vi/ZfhnFr-1MPo/mqdefault.jpg",
            "channelTitle": "Unacademy",
            "publishedAt": "2024-03-20T11:33:57+00:00"
        },
        {
            "id": "CBDM_OhgQFI",
            "title": "Aarambh - The Journey Begins | Unacademy Centre Foundation Day | June 15, 2023",
            "description": "Educational content from Unacademy.",
            "thumbnail": "https://i.ytimg.com/vi/CBDM_OhgQFI/mqdefault.jpg",
            "channelTitle": "Unacademy",
            "publishedAt": "2023-06-24T08:23:57+00:00"
        },
        {
            "id": "gFPhYguV0ZU",
            "title": "Epic Hide & Seek Ft. @ashishchanchlanivines @SamayRainaOfficial  | Official Challenge",
            "description": "Educational content from Unacademy.",
            "thumbnail": "https://i.ytimg.com/vi/gFPhYguV0ZU/mqdefault.jpg",
            "channelTitle": "Unacademy",
            "publishedAt": "2022-11-26T15:38:46+00:00"
        }
    ]
};

/**
 * Merges live API/RSS results with curated fallback.
 * Live results always appear first; curated fill gaps.
 * Guarantees minimum 3 videos per category.
 */
export function mergeCuratedVideos(
    liveVideos: Record<string, YouTubeVideo[]>
): Record<string, YouTubeVideo[]> {
    const merged: Record<string, YouTubeVideo[]> = {};
    const categories = Object.keys(CURATED_INDIAN_EDU_VIDEOS);

    for (const cat of categories) {
        const live = liveVideos[cat] || [];
        const curated = CURATED_INDIAN_EDU_VIDEOS[cat] || [];
        const seenIds = new Set(live.map((v) => v.id));
        const extras = curated.filter((v) => !seenIds.has(v.id));
        merged[cat] = [...live, ...extras].slice(0, 6);
    }

    return merged;
}
