#!/usr/bin/env python3
"""Generate docs/flutter/SESSION_REPORT.md from the loop's own records.

    python3 scripts/loop/session_report.py [--out docs/flutter/SESSION_REPORT.md]

WHY THIS IS A SCRIPT

The report is the artefact a human reads to decide whether to trust the run.
If the agent that did the work also writes the summary of the work, the summary
is the least reliable document in the repository -- that is exactly how the four
archived trackers came to claim a golden-test gate that had no implementation
behind it.

So every number here is read from WAKE_LOG.jsonl (append-only, never rewritten)
and LOOP_STATE.json's `.machine` subtree (overwritten wholesale by reconcile.py
from the repo each wake). Nothing is passed in. Nothing is retyped. A wake that
shipped nothing appears as a wake that shipped nothing, because the log has a
row for it either way and this script does not filter.

The one thing the script must never do is decide what counts as progress. It
prints what the log says. Judgement stays with the reader.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import time
from collections import Counter
from pathlib import Path

APP_ROOT = Path(__file__).resolve().parents[2]
STATE = APP_ROOT / "docs/flutter/loop/LOOP_STATE.json"
WAKE_LOG = APP_ROOT / "docs/flutter/loop/WAKE_LOG.jsonl"
CLAIMS = APP_ROOT / "docs/flutter/loop/CLAIMS.tsv"

# Bookkeeping-only statuses, kept distinct from work outcomes in the tally.
TERMINAL = ("done", "blocked", "failed", "quarantined")


def sh(*args: str) -> str:
    r = subprocess.run(args, cwd=APP_ROOT, capture_output=True, text=True)
    return r.stdout.strip()


def read_wakes() -> list[dict]:
    if not WAKE_LOG.exists():
        return []
    out = []
    for line in WAKE_LOG.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            # A corrupt line is itself a finding; surface it rather than drop it.
            out.append({"unit": "<unparseable log line>", "status": "?",
                        "_raw": line[:200]})
    return out


def hhmm(epoch: int | None) -> str:
    if not epoch:
        return "--:--"
    return time.strftime("%H:%M", time.localtime(epoch))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="docs/flutter/SESSION_REPORT.md")
    a = ap.parse_args()

    state = json.loads(STATE.read_text(encoding="utf-8"))
    queue = state.get("queue", [])
    machine = state.get("machine", {})
    loop = state.get("loop", {})
    wakes = read_wakes()

    by_id = {u["id"]: u for u in queue}
    status_count = Counter(u.get("status", "?") for u in queue)

    head = sh("git", "rev-parse", "HEAD")
    branch = sh("git", "rev-parse", "--abbrev-ref", "HEAD")
    ahead = sh("git", "rev-list", "--count", "origin/main..HEAD")

    L: list[str] = []
    w = L.append

    w("# SahayakAI Flutter — autonomous build session report")
    w("")
    w("Generated by `scripts/loop/session_report.py` from `WAKE_LOG.jsonl` and")
    w("the machine-derived subtree of `LOOP_STATE.json`. No figure in this file")
    w("was typed by an agent. A wake that shipped nothing appears below as a")
    w("wake that shipped nothing.")
    w("")
    w(f"- Branch `{branch}` at `{head[:9]}`, {ahead} commits ahead of `origin/main`")
    w(f"- {len(wakes)} recorded wakes")
    w(f"- Generated {time.strftime('%Y-%m-%d %H:%M %Z')}")
    w("")

    # ── machine facts ────────────────────────────────────────────────────────
    w("## Machine-verified state at HEAD")
    w("")
    w("Re-derived from the repository by `reconcile.sh` on the last wake, not")
    w("carried forward from any earlier claim.")
    w("")
    tests = machine.get("tests", {})
    i18n = machine.get("i18n", {})
    claims = machine.get("claims", {})
    w("| Measure | Value |")
    w("|---|---|")
    w(f"| Test declarations | {tests.get('declarations', '?')} |")
    w(f"| Tests skipped | {tests.get('skipped', '?')} |")
    w(f"| Golden call sites | {tests.get('goldenCallSites', '?')} |")
    w(f"| Untranslated i18n keys | {i18n.get('untranslatedTotal', '?')} |")
    w(f"| Identical-to-English keys | {i18n.get('identicalToEnglishTotal', '?')} |")
    w(f"| Doc claims green / red | {claims.get('green', '?')} / {claims.get('red', '?')} |")
    w("")

    # ── unit outcomes ────────────────────────────────────────────────────────
    w("## Unit outcomes")
    w("")
    w("| Status | Count |")
    w("|---|---|")
    for s, n in sorted(status_count.items(), key=lambda kv: -kv[1]):
        w(f"| {s} | {n} |")
    w("")
    w("`stale` is auto-decay, not failure: a unit recorded `done` at a sha is")
    w("demoted when a later unit touches its files, so the tracker cannot keep")
    w("asserting a green that nothing has re-checked. The landing `release`")
    w("gate re-verifies HEAD wholesale.")
    w("")

    # ── blocked, with the reason ────────────────────────────────────────────
    blocked = [u for u in queue if u.get("status") == "blocked"]
    if blocked:
        w("## Blocked on a human")
        w("")
        w("Each of these is finished work that the loop is not permitted to")
        w("complete. The blocker kind is a closed enum, so an agent cannot")
        w("invent a softer-sounding reason.")
        w("")
        w("| Unit | Kind | Detail |")
        w("|---|---|---|")
        for u in blocked:
            b = u.get("blockedBy") or {}
            detail = (b.get("detail") or "").replace("|", "\\|")
            w(f"| {u['id']} | {b.get('kind', '?')} | {detail} |")
        w("")

    # ── failures, verbatim ──────────────────────────────────────────────────
    failed = [u for u in queue if u.get("status") == "failed"]
    w("## Failures")
    w("")
    if not failed:
        w("No unit ended this run in `failed`.")
    else:
        for u in failed:
            f = u.get("failure") or {}
            w(f"### {u['id']} — {u.get('title', '')}")
            w("")
            w(f"Failed at rung `{f.get('gate')}` with exit `{f.get('exit')}`.")
            w("")
            w("```")
            w(str(f.get("tail") or "(no output captured)"))
            w("```")
            w("")
    w("")

    # ── the wake log itself ─────────────────────────────────────────────────
    w("## Wake log")
    w("")
    w("Every recorded wake, in order, unfiltered.")
    w("")
    w("| # | Time | Unit | Status | Gate | Commit |")
    w("|---|---|---|---|---|---|")
    for e in wakes:
        gate = e.get("gateProfile")
        gx = e.get("gateExit")
        gate_cell = "—" if gate is None else f"{gate}:{gx}"
        commit = (e.get("commit") or "")[:9] or "—"
        w(f"| {e.get('wake', '?')} | {hhmm(e.get('atEpoch'))} | "
          f"{e.get('unit', '?')} | {e.get('status', '?')} | {gate_cell} | {commit} |")
    w("")

    # ── claims ──────────────────────────────────────────────────────────────
    if CLAIMS.exists():
        rows = [r for r in CLAIMS.read_text(encoding="utf-8").splitlines()
                if r.strip() and not r.lstrip().startswith("#")]
        w("## Checkable documentation claims")
        w("")
        w(f"`CLAIMS.tsv` carries {len(rows)} assertions, each with the command")
        w("that confirms it. `doc_truth_guard.sh` runs them; a doc may only")
        w("assert what a command confirms.")
        w("")

    out = APP_ROOT / a.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"session_report: wrote {a.out} "
          f"({len(wakes)} wakes, {len(queue)} units, head={head[:9]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
