/**
 * Data Portability Contract Clauses
 *
 * Templates for school/government contracts that guarantee data portability.
 * These are legal clause templates — must be reviewed by legal counsel before use.
 *
 * Compliance: India DPDP Act 2023, Section 6(7) — Right to Data Portability
 */

export const DATA_PORTABILITY_CLAUSES = {

  /**
   * Standard clause for school contracts (B2B).
   */
  schoolContract: `
DATA PORTABILITY AND EXPORT RIGHTS

1. DATA OWNERSHIP
   1.1 All content generated by School's teachers using the Platform ("Teacher Content")
       — including but not limited to lesson plans, quizzes, worksheets, rubrics,
       visual aids, and assessment materials — is and shall remain the intellectual
       property of the respective teacher and/or the School.

   1.2 SargVision Technologies Pvt. Ltd. ("Provider") claims no ownership rights
       over Teacher Content. The Provider's license to Teacher Content is limited
       to storing, processing, and displaying it within the Platform for the
       duration of the subscription.

2. EXPORT FORMATS
   2.1 The School and its teachers may export all Teacher Content at any time
       during the subscription period in the following formats:
       (a) JSON — machine-readable, structured data
       (b) PDF — universally readable documents
       (c) HTML — editable, print-ready documents
       (d) CSV — usage analytics and content inventories
       (e) Google Forms-compatible JSON — for quizzes and assessments

   2.2 Exports shall be delivered as a single ZIP archive containing all
       content organized by type, accompanied by a machine-readable manifest.

3. SELF-SERVICE EXPORT
   3.1 Individual teachers may initiate a complete data export at any time
       through the Platform's Settings interface.

   3.2 The School Administrator may initiate a bulk export covering all
       teachers associated with the School.

   3.3 Exports for fewer than 500 content items shall be available for
       immediate download. Larger exports shall be processed within 24 hours
       with a download link valid for 48 hours.

4. SUBSCRIPTION TERMINATION
   4.1 Upon termination or non-renewal of this Agreement:
       (a) The School shall have a grace period of thirty (30) calendar days
           to export all Teacher Content.
       (b) The Provider shall send export reminders to the School Administrator
           at days 1, 7, 21, and 28 of the grace period.
       (c) After the grace period, the Provider shall anonymize personally
           identifiable information but shall retain Teacher Content in
           read-only mode for an additional sixty (60) days.
       (d) After ninety (90) days from termination, all data shall be
           permanently deleted unless a legal hold is in effect.

5. DATA ESCROW (Enterprise/Government tier)
   5.1 For contracts exceeding INR 10,00,000 (Ten Lakhs) annually, the Provider
       shall, upon request, enter into a data escrow agreement with a mutually
       agreed third-party escrow agent.

   5.2 The escrow deposit shall include:
       (a) A complete, current backup of all School data in the formats
           specified in Section 2.
       (b) Updated quarterly or upon material changes.

   5.3 Release conditions: The escrow data shall be released to the School if:
       (a) The Provider ceases business operations;
       (b) The Provider enters insolvency, liquidation, or administration;
       (c) The Provider materially breaches this Agreement and fails to cure
           within thirty (30) days of written notice.

6. SOURCE CODE ESCROW (Government contracts only)
   6.1 For state or central government contracts, the Provider shall deposit
       a copy of the Platform's source code with a recognized escrow agent
       (e.g., Iron Mountain, NCC Group, or an Indian equivalent).

   6.2 The source code escrow shall be updated with each major version release.

   6.3 Release conditions are identical to Section 5.3.

7. DPDP ACT COMPLIANCE
   7.1 This clause is provided in compliance with the Digital Personal Data
       Protection Act, 2023 (India), Section 6(7), which grants Data Principals
       the right to obtain their personal data in a commonly used,
       machine-readable format.

   7.2 The Provider shall respond to any data portability request within
       seventy-two (72) hours.

8. AUTOMATED BACKUPS
   8.1 The Provider shall send a monthly usage summary to the School
       Administrator via email, including a one-click link to initiate
       a full data export.

   8.2 Upon request, the Provider shall enable automatic synchronization
       of generated content to the School's designated Google Workspace
       (Google Drive) folder.

9. SURVIVAL
   9.1 The obligations in this section shall survive termination of this
       Agreement for a period of ninety (90) days.
  `,

  /**
   * Abbreviated clause for individual teacher terms of service.
   */
  teacherTOS: `
YOUR DATA RIGHTS

You own everything you create on SahayakAI. We store it for you, but it belongs to you.

- Download anytime: Go to Settings > Export Data to download all your lesson plans,
  quizzes, worksheets, and other content as a ZIP file.
- Multiple formats: Your content is available in JSON (data), HTML (printable),
  and CSV (spreadsheet).
- If you leave: After cancellation, you have 30 days to download everything.
  We'll remind you at day 1, 7, 21, and 28. After 30 days, your personal information
  is anonymized, but your content stays accessible in read-only mode for 60 more days.
- DPDP Act: Under the Digital Personal Data Protection Act 2023, you have the right
  to receive your data in a machine-readable format. We honor this within 72 hours.
  `,

  /**
   * Government MoU addendum for data sovereignty.
   */
  governmentAddendum: `
DATA SOVEREIGNTY ADDENDUM

1. All data generated under this MoU shall be stored within the territory of India,
   on servers located in the GCP asia-south1 (Mumbai) or asia-south2 (Delhi) regions.

2. No Teacher Content or personally identifiable information shall be transferred
   outside India without the prior written consent of the Government Authority.

3. The Provider shall maintain SOC 2 Type II compliance or equivalent Indian
   certification (e.g., STQC) within 18 months of contract execution.

4. Source code escrow per Section 6 of the Data Portability clause is mandatory
   for all government contracts.

5. Upon contract conclusion, the Provider shall provide a complete data handover
   package to the Government Authority within fifteen (15) business days, in
   formats compatible with NIC/DIKSHA infrastructure (JSON-LD, QTI for assessments).
  `,
};
